/*
Nager.Date API - V3

Testing PublicHolidayAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PublicHolidayAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicHolidayAPIService PublicHolidayIsTodayPublicHoliday", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var countryCode string

		httpRes, err := apiClient.PublicHolidayAPI.PublicHolidayIsTodayPublicHoliday(context.Background(), countryCode).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicHolidayAPIService PublicHolidayNextPublicHolidays", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var countryCode string

		resp, httpRes, err := apiClient.PublicHolidayAPI.PublicHolidayNextPublicHolidays(context.Background(), countryCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicHolidayAPIService PublicHolidayNextPublicHolidaysWorldwide", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicHolidayAPI.PublicHolidayNextPublicHolidaysWorldwide(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicHolidayAPIService PublicHolidayPublicHolidaysV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var year int32
		var countryCode string

		resp, httpRes, err := apiClient.PublicHolidayAPI.PublicHolidayPublicHolidaysV3(context.Background(), year, countryCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
